package com.baresudoku;

final class Strings {
    static final String[] TABLE = {
        "en\\nEnglish\\nEasy\\nMedium\\nHard\\nExpert\\nUndo\\nErase\\nNotes\\nFill notes\\nHint\\nNew game\\nShow mistakes\\nOn\\nOff\\nCancel\\nSolved!\\nPreparing…\\nThis digit is wrong\\nOnly one candidate here: #\\nOnly place for # in this row\\nOnly place for # in this column\\nOnly place for # in this box\\nTap hint again to place it\\nLocked candidates\\nPair or triple\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nLanguage\\nAndroid app\\nSource code",
        "tr\\nTürkçe\\nKolay\\nOrta\\nZor\\nUzman\\nGeri al\\nSil\\nNot\\nNotları doldur\\nİpucu\\nYeni oyun\\nYanlışları göster\\nAçık\\nKapalı\\nVazgeç\\nTebrikler!\\nHazırlanıyor…\\nBu rakam yanlış\\nBu hücrede tek aday: #\\nBu satırda # için tek yer\\nBu sütunda # için tek yer\\nBu kutuda # için tek yer\\nYerleştirmek için ipucuna tekrar bas\\nKilitli adaylar\\nÇift veya üçlü\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nDil\\nAndroid uygulaması\\nKaynak kod",
        "az\\nAzərbaycanca\\nAsan\\nOrta\\nÇətin\\nEkspert\\nGeri al\\nSil\\nQeydlər\\nQeydləri doldur\\nİpucu\\nYeni oyun\\nSəhvləri göstər\\nAçıq\\nBağlı\\nLəğv et\\nHəll olundu!\\nHazırlanır…\\nBu rəqəm səhvdir\\nBurada yalnız bir namizəd: #\\nBu sətirdə # üçün yeganə yer\\nBu sütunda # üçün yeganə yer\\nBu blokda # üçün yeganə yer\\nYerləşdirmək üçün İpucuna yenidən toxunun\\nKilidlənmiş namizədlər\\nCüt və ya üçlük\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nDil\\nAndroid tətbiqi\\nMənbə kodu",
        "de\\nDeutsch\\nLeicht\\nMittel\\nSchwer\\nExperte\\nRückgängig\\nLöschen\\nNotizen\\nNotizen füllen\\nTipp\\nNeues Spiel\\nFehler anzeigen\\nAn\\nAus\\nAbbrechen\\nGelöst!\\nWird vorbereitet…\\nDiese Ziffer ist falsch\\nHier nur ein Kandidat: #\\nEinziger Platz für # in dieser Zeile\\nEinziger Platz für # in dieser Spalte\\nEinziger Platz für # in diesem Block\\nTipp erneut antippen, um zu setzen\\nBlockierte Kandidaten\\nPaar oder Tripel\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nSprache\\nAndroid-App\\nQuellcode",
        "fr\\nFrançais\\nFacile\\nMoyen\\nDifficile\\nExpert\\nAnnuler\\nEffacer\\nNotes\\nRemplir les notes\\nIndice\\nNouvelle partie\\nAfficher les erreurs\\nActivé\\nDésactivé\\nFermer\\nRésolu !\\nPréparation…\\nCe chiffre est faux\\nUn seul candidat ici : #\\nSeule place pour # dans cette ligne\\nSeule place pour # dans cette colonne\\nSeule place pour # dans ce bloc\\nAppuyez encore sur Indice pour placer\\nCandidats bloqués\\nPaire ou triplet\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nLangue\\nApplication Android\\nCode source",
        "es\\nEspañol\\nFácil\\nMedio\\nDifícil\\nExperto\\nDeshacer\\nBorrar\\nNotas\\nRellenar notas\\nPista\\nNueva partida\\nMostrar errores\\nSí\\nNo\\nCancelar\\n¡Resuelto!\\nPreparando…\\nEste número es incorrecto\\nSolo un candidato aquí: #\\nÚnico lugar para # en esta fila\\nÚnico lugar para # en esta columna\\nÚnico lugar para # en este bloque\\nPulsa Pista de nuevo para colocarlo\\nCandidatos bloqueados\\nPar o trío\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nIdioma\\nApp para Android\\nCódigo fuente",
        "pt\\nPortuguês\\nFácil\\nMédio\\nDifícil\\nEspecialista\\nDesfazer\\nApagar\\nNotas\\nPreencher notas\\nDica\\nNovo jogo\\nMostrar erros\\nLigado\\nDesligado\\nCancelar\\nResolvido!\\nA preparar…\\nEste número está errado\\nSó um candidato aqui: #\\nÚnico lugar para # nesta linha\\nÚnico lugar para # nesta coluna\\nÚnico lugar para # neste bloco\\nToque em Dica de novo para colocar\\nCandidatos bloqueados\\nPar ou trio\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nIdioma\\nApp Android\\nCódigo-fonte",
        "it\\nItaliano\\nFacile\\nMedio\\nDifficile\\nEsperto\\nAnnulla\\nCancella\\nNote\\nRiempi note\\nSuggerimento\\nNuova partita\\nMostra errori\\nSì\\nNo\\nChiudi\\nRisolto!\\nPreparazione…\\nQuesta cifra è sbagliata\\nUn solo candidato qui: #\\nUnico posto per # in questa riga\\nUnico posto per # in questa colonna\\nUnico posto per # in questo blocco\\nTocca di nuovo Suggerimento per inserirlo\\nCandidati bloccati\\nCoppia o tripla\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nLingua\\nApp Android\\nCodice sorgente",
        "nl\\nNederlands\\nMakkelijk\\nGemiddeld\\nMoeilijk\\nExpert\\nOngedaan maken\\nWissen\\nNotities\\nNotities vullen\\nHint\\nNieuw spel\\nFouten tonen\\nAan\\nUit\\nAnnuleren\\nOpgelost!\\nVoorbereiden…\\nDit cijfer is fout\\nHier maar één kandidaat: #\\nEnige plek voor # in deze rij\\nEnige plek voor # in deze kolom\\nEnige plek voor # in dit blok\\nTik nogmaals op Hint om te plaatsen\\nGeblokkeerde kandidaten\\nPaar of drietal\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nTaal\\nAndroid-app\\nBroncode",
        "pl\\nPolski\\nŁatwy\\nŚredni\\nTrudny\\nEkspert\\nCofnij\\nWymaż\\nNotatki\\nWypełnij notatki\\nPodpowiedź\\nNowa gra\\nPokazuj błędy\\nWł.\\nWył.\\nAnuluj\\nRozwiązane!\\nPrzygotowywanie…\\nTa cyfra jest błędna\\nTylko jeden kandydat tutaj: #\\nJedyne miejsce dla # w tym wierszu\\nJedyne miejsce dla # w tej kolumnie\\nJedyne miejsce dla # w tym bloku\\nDotknij Podpowiedź ponownie, aby wstawić\\nZablokowani kandydaci\\nPara lub trójka\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nJęzyk\\nAplikacja na Androida\\nKod źródłowy",
        "cs\\nČeština\\nLehká\\nStřední\\nTěžká\\nExpert\\nZpět\\nSmazat\\nPoznámky\\nVyplnit poznámky\\nNápověda\\nNová hra\\nZobrazit chyby\\nZapnuto\\nVypnuto\\nZrušit\\nVyřešeno!\\nPřipravuje se…\\nTato číslice je špatně\\nJediný kandidát zde: #\\nJediné místo pro # v tomto řádku\\nJediné místo pro # v tomto sloupci\\nJediné místo pro # v tomto bloku\\nKlepněte znovu na Nápovědu pro vložení\\nUzamčení kandidáti\\nDvojice nebo trojice\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nJazyk\\nAplikace pro Android\\nZdrojový kód",
        "sk\\nSlovenčina\\nĽahká\\nStredná\\nŤažká\\nExpert\\nSpäť\\nVymazať\\nPoznámky\\nVyplniť poznámky\\nPomôcka\\nNová hra\\nZobraziť chyby\\nZapnuté\\nVypnuté\\nZrušiť\\nVyriešené!\\nPripravuje sa…\\nTáto číslica je nesprávna\\nJediný kandidát tu: #\\nJediné miesto pre # v tomto riadku\\nJediné miesto pre # v tomto stĺpci\\nJediné miesto pre # v tomto bloku\\nŤuknite znova na Pomôcku pre vloženie\\nUzamknutí kandidáti\\nDvojica alebo trojica\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nJazyk\\nAplikácia pre Android\\nZdrojový kód",
        "hu\\nMagyar\\nKönnyű\\nKözepes\\nNehéz\\nSzakértő\\nVisszavonás\\nTörlés\\nJegyzetek\\nJegyzetek kitöltése\\nTipp\\nÚj játék\\nHibák mutatása\\nBe\\nKi\\nMégse\\nMegoldva!\\nElőkészítés…\\nEz a szám hibás\\nCsak egy jelölt itt: #\\nAz egyetlen hely a # számára ebben a sorban\\nAz egyetlen hely a # számára ebben az oszlopban\\nAz egyetlen hely a # számára ebben a blokkban\\nÉrintsd meg újra a Tippet a beírásához\\nZárt jelöltek\\nPár vagy hármas\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nNyelv\\nAndroid-alkalmazás\\nForráskód",
        "ro\\nRomână\\nUșor\\nMediu\\nGreu\\nExpert\\nAnulează\\nȘterge\\nNotițe\\nUmple notițele\\nIndiciu\\nJoc nou\\nArată greșelile\\nPornit\\nOprit\\nRenunță\\nRezolvat!\\nSe pregătește…\\nAceastă cifră este greșită\\nUn singur candidat aici: #\\nSingurul loc pentru # pe acest rând\\nSingurul loc pentru # pe această coloană\\nSingurul loc pentru # în acest bloc\\nAtinge din nou Indiciu pentru a plasa\\nCandidați blocați\\nPereche sau triplet\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nLimbă\\nAplicație Android\\nCod sursă",
        "el\\nΕλληνικά\\nΕύκολο\\nΜέτριο\\nΔύσκολο\\nΕιδικός\\nΑναίρεση\\nΣβήσιμο\\nΣημειώσεις\\nΣυμπλήρωση σημειώσεων\\nΒοήθεια\\nΝέο παιχνίδι\\nΕμφάνιση λαθών\\nΝαι\\nΌχι\\nΆκυρο\\nΛύθηκε!\\nΠροετοιμασία…\\nΑυτό το ψηφίο είναι λάθος\\nΜόνο ένας υποψήφιος εδώ: #\\nΜοναδική θέση για το # σε αυτή τη γραμμή\\nΜοναδική θέση για το # σε αυτή τη στήλη\\nΜοναδική θέση για το # σε αυτό το κουτί\\nΠατήστε ξανά Βοήθεια για τοποθέτηση\\nΚλειδωμένοι υποψήφιοι\\nΖευγάρι ή τριάδα\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nΓλώσσα\\nΕφαρμογή Android\\nΠηγαίος κώδικας",
        "sv\\nSvenska\\nLätt\\nMedel\\nSvår\\nExpert\\nÅngra\\nRadera\\nAnteckningar\\nFyll i anteckningar\\nLedtråd\\nNytt spel\\nVisa fel\\nPå\\nAv\\nAvbryt\\nLöst!\\nFörbereder…\\nDen här siffran är fel\\nBara en kandidat här: #\\nEnda platsen för # på den här raden\\nEnda platsen för # i den här kolumnen\\nEnda platsen för # i den här rutan\\nTryck på Ledtråd igen för att placera\\nLåsta kandidater\\nPar eller trippel\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nSpråk\\nAndroid-app\\nKällkod",
        "da\\nDansk\\nLet\\nMellem\\nSvær\\nEkspert\\nFortryd\\nSlet\\nNoter\\nUdfyld noter\\nHint\\nNyt spil\\nVis fejl\\nTil\\nFra\\nAnnuller\\nLøst!\\nForbereder…\\nDette tal er forkert\\nKun én kandidat her: #\\nEneste plads til # i denne række\\nEneste plads til # i denne kolonne\\nEneste plads til # i denne boks\\nTryk på Hint igen for at placere\\nLåste kandidater\\nPar eller triple\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nSprog\\nAndroid-app\\nKildekode",
        "nb\\nNorsk\\nLett\\nMiddels\\nVanskelig\\nEkspert\\nAngre\\nSlett\\nNotater\\nFyll notater\\nHint\\nNytt spill\\nVis feil\\nPå\\nAv\\nAvbryt\\nLøst!\\nForbereder…\\nDette tallet er feil\\nBare én kandidat her: #\\nEneste plass for # i denne raden\\nEneste plass for # i denne kolonnen\\nEneste plass for # i denne boksen\\nTrykk på Hint igjen for å plassere\\nLåste kandidater\\nPar eller trippel\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nSpråk\\nAndroid-app\\nKildekode",
        "fi\\nSuomi\\nHelppo\\nKeskitaso\\nVaikea\\nAsiantuntija\\nKumoa\\nPyyhi\\nMuistiinpanot\\nTäytä muistiinpanot\\nVihje\\nUusi peli\\nNäytä virheet\\nPäällä\\nPois\\nPeruuta\\nRatkaistu!\\nValmistellaan…\\nTämä numero on väärin\\nVain yksi ehdokas tässä: #\\nAinoa paikka numerolle # tällä rivillä\\nAinoa paikka numerolle # tässä sarakkeessa\\nAinoa paikka numerolle # tässä ruudukossa\\nNapauta Vihjettä uudelleen sijoittaaksesi\\nLukitut ehdokkaat\\nPari tai kolmikko\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nKieli\\nAndroid-sovellus\\nLähdekoodi",
        "ru\\nРусский\\nЛегко\\nСредне\\nСложно\\nЭксперт\\nОтменить\\nСтереть\\nЗаметки\\nЗаполнить заметки\\nПодсказка\\nНовая игра\\nПоказывать ошибки\\nВкл\\nВыкл\\nЗакрыть\\nРешено!\\nПодготовка…\\nЭта цифра неверна\\nЗдесь только один кандидат: #\\nЕдинственное место для # в этой строке\\nЕдинственное место для # в этом столбце\\nЕдинственное место для # в этом блоке\\nНажмите Подсказку ещё раз, чтобы поставить\\nЗаблокированные кандидаты\\nПара или тройка\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nЯзык\\nПриложение для Android\\nИсходный код",
        "uk\\nУкраїнська\\nЛегко\\nСередньо\\nСкладно\\nЕксперт\\nСкасувати\\nСтерти\\nНотатки\\nЗаповнити нотатки\\nПідказка\\nНова гра\\nПоказувати помилки\\nУвімк\\nВимк\\nЗакрити\\nРозв'язано!\\nПідготовка…\\nЦя цифра неправильна\\nТут лише один кандидат: #\\nЄдине місце для # у цьому рядку\\nЄдине місце для # у цьому стовпці\\nЄдине місце для # у цьому блоці\\nНатисніть Підказку ще раз, щоб поставити\\nЗаблоковані кандидати\\nПара або трійка\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nМова\\nЗастосунок для Android\\nВихідний код",
        "bg\\nБългарски\\nЛесно\\nСредно\\nТрудно\\nЕксперт\\nОтмени\\nИзтрий\\nБележки\\nПопълни бележките\\nПодсказка\\nНова игра\\nПоказвай грешките\\nВкл\\nИзкл\\nЗатвори\\nРешено!\\nПодготовка…\\nТази цифра е грешна\\nСамо един кандидат тук: #\\nЕдинствено място за # в този ред\\nЕдинствено място за # в тази колона\\nЕдинствено място за # в това каре\\nНатиснете Подсказка отново, за да поставите\\nЗаключени кандидати\\nДвойка или тройка\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nЕзик\\nПриложение за Android\\nИзходен код",
        "sr\\nSrpski\\nLako\\nSrednje\\nTeško\\nEkspert\\nOpozovi\\nObriši\\nBeleške\\nPopuni beleške\\nSavet\\nNova igra\\nPrikaži greške\\nUključeno\\nIsključeno\\nOtkaži\\nRešeno!\\nPriprema…\\nOva cifra je pogrešna\\nSamo jedan kandidat ovde: #\\nJedino mesto za # u ovom redu\\nJedino mesto za # u ovoj koloni\\nJedino mesto za # u ovom bloku\\nDodirnite Savet ponovo da biste upisali\\nZaključani kandidati\\nPar ili trojka\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nJezik\\nAndroid aplikacija\\nIzvorni kod",
        "hr\\nHrvatski\\nLako\\nSrednje\\nTeško\\nEkspert\\nPoništi\\nObriši\\nBilješke\\nPopuni bilješke\\nSavjet\\nNova igra\\nPrikaži pogreške\\nUključeno\\nIsključeno\\nOdustani\\nRiješeno!\\nPriprema…\\nOva znamenka je pogrešna\\nSamo jedan kandidat ovdje: #\\nJedino mjesto za # u ovom retku\\nJedino mjesto za # u ovom stupcu\\nJedino mjesto za # u ovom bloku\\nDodirnite Savjet ponovno za upis\\nZaključani kandidati\\nPar ili trojka\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nJezik\\nAndroid aplikacija\\nIzvorni kod",
        "ar\\nالعربية\\nسهل\\nمتوسط\\nصعب\\nخبير\\nتراجع\\nمسح\\nملاحظات\\nملء الملاحظات\\nتلميح\\nلعبة جديدة\\nإظهار الأخطاء\\nتشغيل\\nإيقاف\\nإلغاء\\nتم الحل!\\nجارٍ التحضير…\\nهذا الرقم خاطئ\\nمرشح واحد فقط هنا: #\\nالمكان الوحيد للرقم # في هذا الصف\\nالمكان الوحيد للرقم # في هذا العمود\\nالمكان الوحيد للرقم # في هذا المربع\\nاضغط التلميح مرة أخرى للوضع\\nمرشحون محصورون\\nزوج أو ثلاثي\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nاللغة\\nتطبيق أندرويد\\nالكود المصدري",
        "fa\\nفارسی\\nآسان\\nمتوسط\\nسخت\\nحرفه‌ای\\nواگرد\\nپاک کردن\\nیادداشت‌ها\\nپر کردن یادداشت‌ها\\nراهنمایی\\nبازی جدید\\nنمایش اشتباه‌ها\\nروشن\\nخاموش\\nانصراف\\nحل شد!\\nدر حال آماده‌سازی…\\nاین رقم اشتباه است\\nفقط یک نامزد اینجا: #\\nتنها جای # در این سطر\\nتنها جای # در این ستون\\nتنها جای # در این جعبه\\nبرای قرار دادن دوباره راهنمایی را بزنید\\nنامزدهای قفل‌شده\\nجفت یا سه‌تایی\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nزبان\\nبرنامه اندروید\\nکد منبع",
        "he\\nעברית\\nקל\\nבינוני\\nקשה\\nמומחה\\nבטל\\nמחק\\nהערות\\nמלא הערות\\nרמז\\nמשחק חדש\\nהצג טעויות\\nפועל\\nכבוי\\nביטול\\nנפתר!\\nמכין…\\nהספרה הזו שגויה\\nרק מועמד אחד כאן: #\\nהמקום היחיד ל-# בשורה הזו\\nהמקום היחיד ל-# בעמודה הזו\\nהמקום היחיד ל-# בריבוע הזה\\nהקש שוב על רמז כדי להציב\\nמועמדים נעולים\\nזוג או שלשה\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nשפה\\nאפליקציית אנדרואיד\\nקוד מקור",
        "hi\\nहिन्दी\\nआसान\\nमध्यम\\nकठिन\\nविशेषज्ञ\\nपूर्ववत\\nमिटाएँ\\nनोट्स\\nनोट्स भरें\\nसंकेत\\nनया खेल\\nगलतियाँ दिखाएँ\\nचालू\\nबंद\\nरद्द करें\\nहल हो गया!\\nतैयार हो रहा है…\\nयह अंक गलत है\\nयहाँ केवल एक उम्मीदवार: #\\nइस पंक्ति में # के लिए एकमात्र स्थान\\nइस स्तंभ में # के लिए एकमात्र स्थान\\nइस बॉक्स में # के लिए एकमात्र स्थान\\nरखने के लिए संकेत फिर दबाएँ\\nबंद उम्मीदवार\\nजोड़ी या तिकड़ी\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nभाषा\\nAndroid ऐप\\nस्रोत कोड",
        "bn\\nবাংলা\\nসহজ\\nমাঝারি\\nকঠিন\\nবিশেষজ্ঞ\\nপূর্বাবস্থা\\nমুছুন\\nনোট\\nনোট পূরণ করুন\\nইঙ্গিত\\nনতুন খেলা\\nভুল দেখান\\nচালু\\nবন্ধ\\nবাতিল\\nসমাধান হয়েছে!\\nপ্রস্তুত হচ্ছে…\\nএই সংখ্যাটি ভুল\\nএখানে শুধু একটি প্রার্থী: #\\nএই সারিতে # এর একমাত্র স্থান\\nএই কলামে # এর একমাত্র স্থান\\nএই বক্সে # এর একমাত্র স্থান\\nবসাতে আবার ইঙ্গিত চাপুন\\nআবদ্ধ প্রার্থী\\nজোড়া বা ত্রয়ী\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nভাষা\\nAndroid অ্যাপ\\nসোর্স কোড",
        "id\\nBahasa Indonesia\\nMudah\\nSedang\\nSulit\\nAhli\\nUrungkan\\nHapus\\nCatatan\\nIsi catatan\\nPetunjuk\\nPermainan baru\\nTampilkan kesalahan\\nAktif\\nNonaktif\\nBatal\\nTerpecahkan!\\nMenyiapkan…\\nAngka ini salah\\nHanya satu kandidat di sini: #\\nSatu-satunya tempat untuk # di baris ini\\nSatu-satunya tempat untuk # di kolom ini\\nSatu-satunya tempat untuk # di kotak ini\\nKetuk Petunjuk lagi untuk menempatkan\\nKandidat terkunci\\nPasangan atau tripel\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nBahasa\\nAplikasi Android\\nKode sumber",
        "ms\\nBahasa Melayu\\nMudah\\nSederhana\\nSukar\\nPakar\\nBuat asal\\nPadam\\nNota\\nIsi nota\\nPetunjuk\\nPermainan baharu\\nTunjukkan kesilapan\\nHidup\\nMati\\nBatal\\nSelesai!\\nMenyediakan…\\nAngka ini salah\\nHanya satu calon di sini: #\\nSatu-satunya tempat untuk # dalam baris ini\\nSatu-satunya tempat untuk # dalam lajur ini\\nSatu-satunya tempat untuk # dalam kotak ini\\nKetik Petunjuk sekali lagi untuk meletakkan\\nCalon terkunci\\nPasangan atau tiga\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nBahasa\\nAplikasi Android\\nKod sumber",
        "vi\\nTiếng Việt\\nDễ\\nTrung bình\\nKhó\\nChuyên gia\\nHoàn tác\\nXóa\\nGhi chú\\nĐiền ghi chú\\nGợi ý\\nVán mới\\nHiện lỗi sai\\nBật\\nTắt\\nHủy\\nĐã giải!\\nĐang chuẩn bị…\\nSố này sai\\nChỉ có một ứng viên ở đây: #\\nVị trí duy nhất cho # trong hàng này\\nVị trí duy nhất cho # trong cột này\\nVị trí duy nhất cho # trong ô này\\nNhấn Gợi ý lần nữa để điền\\nỨng viên bị khóa\\nCặp hoặc bộ ba\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nNgôn ngữ\\nỨng dụng Android\\nMã nguồn",
        "th\\nไทย\\nง่าย\\nปานกลาง\\nยาก\\nผู้เชี่ยวชาญ\\nเลิกทำ\\nลบ\\nโน้ต\\nเติมโน้ต\\nคำใบ้\\nเกมใหม่\\nแสดงข้อผิดพลาด\\nเปิด\\nปิด\\nยกเลิก\\nแก้ได้แล้ว!\\nกำลังเตรียม…\\nตัวเลขนี้ผิด\\nมีตัวเลือกเดียวที่นี่: #\\nที่เดียวสำหรับ # ในแถวนี้\\nที่เดียวสำหรับ # ในคอลัมน์นี้\\nที่เดียวสำหรับ # ในกล่องนี้\\nแตะคำใบ้อีกครั้งเพื่อใส่\\nตัวเลือกที่ถูกล็อก\\nคู่หรือสาม\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\nภาษา\\nแอป Android\\nซอร์สโค้ด",
        "ja\\n日本語\\n簡単\\n普通\\n難しい\\n上級\\n元に戻す\\n消す\\nメモ\\nメモを埋める\\nヒント\\n新しいゲーム\\n間違いを表示\\nオン\\nオフ\\n閉じる\\n解けました！\\n準備中…\\nこの数字は間違いです\\nここの候補は#だけ\\nこの行で#が入るのはここだけ\\nこの列で#が入るのはここだけ\\nこのブロックで#が入るのはここだけ\\nもう一度ヒントを押すと入力されます\\nロックされた候補\\nペアまたはトリプル\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\n言語\\nAndroidアプリ\\nソースコード",
        "ko\\n한국어\\n쉬움\\n보통\\n어려움\\n전문가\\n실행 취소\\n지우기\\n메모\\n메모 채우기\\n힌트\\n새 게임\\n오답 표시\\n켜짐\\n꺼짐\\n닫기\\n해결!\\n준비 중…\\n이 숫자는 틀렸습니다\\n여기의 후보는 #뿐입니다\\n이 행에서 #이 들어갈 곳은 여기뿐\\n이 열에서 #이 들어갈 곳은 여기뿐\\n이 박스에서 #이 들어갈 곳은 여기뿐\\n힌트를 다시 누르면 입력됩니다\\n잠긴 후보\\n쌍 또는 삼중\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\n언어\\nAndroid 앱\\n소스 코드",
        "zh-Hans\\n简体中文\\n简单\\n中等\\n困难\\n专家\\n撤销\\n擦除\\n笔记\\n填充笔记\\n提示\\n新游戏\\n显示错误\\n开\\n关\\n取消\\n已解决！\\n准备中…\\n这个数字错了\\n此处只有一个候选数：#\\n本行中 # 只能放在这里\\n本列中 # 只能放在这里\\n本宫中 # 只能放在这里\\n再按一次提示即可填入\\n区块摒除\\n数对或三链数\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\n语言\\nAndroid 应用\\n源代码",
        "zh-Hant\\n繁體中文\\n簡單\\n中等\\n困難\\n專家\\n復原\\n擦除\\n筆記\\n填入筆記\\n提示\\n新遊戲\\n顯示錯誤\\n開\\n關\\n取消\\n已解開！\\n準備中…\\n這個數字錯了\\n此處只有一個候選數：#\\n本列中 # 只能放在這裡\\n本行中 # 只能放在這裡\\n本宮中 # 只能放在這裡\\n再按一次提示即可填入\\n區塊摒除\\n數對或三鏈數\\nX-Wing\\nY-Wing\\nSwordfish\\nXYZ-Wing\\nBare Sudoku\\n語言\\nAndroid 應用程式\\n原始碼",
    };

    static String[] forTag(String tag) {
        String best = TABLE[0];
        int bestScore = 0;
        for (String entry : TABLE) {
            int score = match(tag, entry.substring(0, entry.indexOf('\n')));
            if (score > bestScore) {
                bestScore = score;
                best = entry;
            }
        }
        String[] parts = best.split("\n");
        String[] out = new String[parts.length - 2];
        System.arraycopy(parts, 2, out, 0, out.length);
        return out;
    }

    static int match(String tag, String code) {
        if (tag.equals(code)) return 3;
        if (tag.startsWith(code + "-")) return 2;
        String lang = language(tag);
        if (lang.equals("zh") && code.equals("zh-Hant") && (tag.contains("TW") || tag.contains("HK") || tag.contains("MO"))) return 2;
        if (lang.equals("no") || lang.equals("nn")) lang = "nb";
        if (lang.equals("iw")) lang = "he";
        if (lang.equals("in")) lang = "id";
        return lang.equals(language(code)) ? 1 : 0;
    }

    static String language(String tag) {
        int dash = tag.indexOf('-');
        return dash > 0 ? tag.substring(0, dash) : tag;
    }
}
